version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - media_data:/app/media:ro
    depends_on:
      - backend
      - frontend

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./certs:/app/certs:ro
      - media_data:/app/media
    expose:
      - "8000"
    environment:
      - DEBUG=0
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=samma_db
      - DB_USER=samma_user
      - DB_PASSWORD=samma_password
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=samma.settings
      - CSRF_TRUSTED_ORIGINS=https://localhost:8443,https://127.0.0.1:8443
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - CORS_ALLOWED_ORIGINS=https://localhost:8443,https://127.0.0.1:8443
      - CORS_ALLOW_CREDENTIALS=1
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    expose:
      - "3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://localhost:8443/api/v1
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    depends_on:
      - backend

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=samma_db
      - POSTGRES_USER=samma_user
      - POSTGRES_PASSWORD=samma_password
    expose:
      - "5432"

  redis:
    image: redis:6-alpine
    expose:
      - "6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  media_data: 