version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - backend
      - frontend

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./certs:/app/certs:ro
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=samma_db
      - DB_USER=samma_user
      - DB_PASSWORD=samma_password
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=samma.settings
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://localhost/api/v1
    depends_on:
      - backend

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=samma_db
      - POSTGRES_USER=samma_user
      - POSTGRES_PASSWORD=samma_password
    ports:
      - "5433:5432"

  redis:
    image: redis:6-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: 