# Generated by Django 4.2.9 on 2025-02-09 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-created_at'], 'verbose_name': 'game', 'verbose_name_plural': 'games'},
        ),
        migrations.RemoveIndex(
            model_name='game',
            name='games_game_ad_scor_645a6d_idx',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ad_score',
        ),
        migrations.RemoveField(
            model_name='game',
            name='additional_images',
        ),
        migrations.RemoveField(
            model_name='game',
            name='bid_percentage',
        ),
        migrations.RemoveField(
            model_name='game',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='game',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='game',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='game',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='game',
            name='total_ratings',
        ),
        migrations.RemoveField(
            model_name='game',
            name='total_sales',
        ),
        migrations.AddField(
            model_name='game',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Main image for the game', null=True, upload_to='game_thumbnails/', verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_file',
            field=models.FileField(blank=True, help_text='Zip file containing the game', null=True, upload_to='game_files/', verbose_name='game file'),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='game',
            name='system_requirements',
            field=models.JSONField(blank=True, default=dict, help_text='Minimum and recommended system requirements', null=True, verbose_name='system requirements'),
        ),
        migrations.AlterField(
            model_name='game',
            name='version',
            field=models.CharField(default='1.0.0', max_length=50, verbose_name='version'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-created_at'], name='games_game_created_1d9304_idx'),
        ),
    ]
