# Generated by Django 4.2.9 on 2025-02-09 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='rating'),
        ),
        migrations.AddField(
            model_name='game',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0, verbose_name='total ratings'),
        ),
        migrations.AddField(
            model_name='game',
            name='total_sales',
            field=models.PositiveIntegerField(default=0, verbose_name='total sales'),
        ),
    ]
