# Generated by Django 4.2.9 on 2025-02-09 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_rating_game_total_ratings_game_total_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bid_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Commission rate percentage (minimum 5%)', max_digits=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)], verbose_name='commission rate'),
        ),
    ]
